# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # VIRTUAL MACHINE CONFIGS
    # Define what box to use (CentOS 8):
    config.vm.box = "centos/8"

    # Set guest options for VirtualBox, including memory (1024), and CPU (2):
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "2"
    end

    # Suppress error caused by ssl inspection
    config.vm.box_download_insecure = true

    # Define hostname (myhost); most useful for environments with multiple guests:
    config.vm.hostname = "MGMTCENTOS8"

    # Configure private network IP address:
    config.vm.network "private_network", ip: "10.0.0.9"

    # Sync files between current local folder and guest /vagrant folder:
    config.vm.synced_folder ".", "/vagrant"

    # INSTALL VB GUEST
    #https://github.com/dotless-de/vagrant-vbguest

    # SET UP SSH KEY BASED AUTHENTICATION
    # https://www.vagrantup.com/docs/provisioning/file
    # For error "mkdir: cannot create directory ‘/home/cyberauto’: Permission denied", see below:
    # https://stackoverflow.com/questions/54067192/vagrant-config-vm-provision-does-not-allow-me-to-copy-a-file-to-etc-nginx-conf
    # Copy cyberauto keys to guest machine
    config.vm.provision "file", source: "../privkeys/id_rsa", destination: "/tmp/id_rsa"
    config.vm.provision "file", source: "../pubkeys/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    config.vm.provision "file", source: "../pubkeys/dtran_id_rsa.pub", destination: "/tmp/dtran_id_rsa.pub"

    # GUEST PROVISION WITH SHELL SCRIPT BOOTSTRAP.SH
    # https://www.vagrantup.com/docs/provisioning/basic_usage
    config.vm.provision "shell", path: "bootstrap.sh"

    #https://github.com/dotless-de/vagrant-vbguest
    #Vagrant::Config.run do |config|
        # we will try to autodetect this path.
        # However, if we cannot or you have a special one you may pass it like:
        # config.vbguest.iso_path = "#{ENV['HOME']}/Downloads/VBoxGuestAdditions.iso"
        # or an URL:
        # config.vbguest.iso_path = "http://company.server/VirtualBox/%{version}/VBoxGuestAdditions.iso"
        # or relative to the Vagrantfile:
        # config.vbguest.iso_path = "../relative/path/to/VBoxGuestAdditions.iso"

        # set auto_update to false, if you do NOT want to check the correct
        # additions version when booting this machine
        #config.vbguest.auto_update = false

        # do NOT download the iso file from a webserver
        #config.vbguest.no_remote = true
    #end

end
